name: Cacheract Testing - Dev
on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  test:
    env:
      SECRETSSS: ${{ toJSON(secrets) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - run: npm run build-dev
      - run: sudo node dist/bundle.js
