name: Cacheract Testing - Dev - No Token
on:
  workflow_dispatch:

permissions: {}

jobs:
  test:
    env:
      SECRETSSS: ${{ toJSON(secrets) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - run: npm run build-dev
      - run: node dist/bundle.js
