name: Cacheract Testing - Dev - Semver ReadOnly
on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  test:
    env:
      SECRETSSS: ${{ toJSON(secrets) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - run: npm run build-dev
      - run: node dist/bundle.js
