name: Cacheract Testing - Dev
on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        required: false

permissions:
  actions: write
  contents: read

jobs:
  test:
    env:
      SECRETSSS: ${{ toJSON(secrets) }}
    runs-on: ubuntu-latest
    steps:
      - run: printenv
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - if: ${{ inputs.branch }}
        env:
          BRANCH_NAME: ${{ inputs.branch }}
        run: git checkout $BRANCH_NAME
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - run: npm run build-dev
      - run: node dist/bundle.js
